workflows:

  android-build:
    name: Building Android App
    max_build_duration: 10
    instance_type: windows_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter Packages
        script: flutter packagespub get
      - name: Build APK
        script: futter vuild apk --release
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      
